// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnpzoyvjenbbimijvjxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpucHpveXZqZW5iYmltaWp2anhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTIyOTUsImV4cCI6MjA2ODkyODI5NX0.2XGE2e20sM84l35_uGiWOAr7F9dAamdIJg7OLVZGoD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});